myproject/core/urls.py
from django.conf.urls import url
from myproject.core import views as c


urlpatterns = [
    url(r'^$', c.home, name='home'),
    url(r'^logged/$', c.LoggedView.as_view(), name='logged'),
    url(r'^director/$', c.DirectorTemplateView.as_view(), name='director'),
]

myproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('myproject.core.urls', namespace='core')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
]

myproject/core/models.py
from django.db import models

# Create your models here.

myproject/myauth/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from django.utils.translation import ugettext_lazy as _

from .managers import UserManager


class User(AbstractBaseUser):
    """
    This is an adaptation of Django's AbstractUser Class
    """
    email = models.EmailField(
        _('email'),
        unique=True,
        help_text=_(
            'Required (use a valid email address).'),
        error_messages={
            'unique': _("A user with that email already exists."),
        },
    )

    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'

    class Meta:
        ordering = ('email',)
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        return self.email

    def has_module_perms(self, app_label):
        return True

    def has_perm(self, perm, obj=None):
        return True

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    @property
    def is_staff(self):
        return True

myproject/myauth/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from .models import User


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('email',)

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('email', 'password', 'is_active', 'is_admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

myproject/core/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from braces.views import LoginRequiredMixin, GroupRequiredMixin


def home(request):
    return render(request, 'index.html')


class LoggedView(LoginRequiredMixin, TemplateView):
    template_name = 'core/logged.html'


class DirectorTemplateView(GroupRequiredMixin, TemplateView):
    template_name = 'core/director.html'
    group_required = u'Diretor'

myproject/myauth/views.py
from registration.views import RegistrationView


class MyView(RegistrationView):

    def post(self, request):
        request.form['username'] = request.form.get('email')
        super().RegistrationView()
    # mudar o atributo do formulário
    # estender o form tb.

myproject/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% block title %}
      <title>Custom-Admin</title>
    {% endblock title %}

    <link rel="shortcut icon" href="https://www.djangoproject.com/favicon.ico">
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static "css/login.css" %}" />
  
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <style type="text/css">
      /* Move down content because we have a fixed navbar that is 50px tall */
      body {
        padding-top: 60px;
        padding-bottom: 40px;
        /*color: #5a5a5a;*/
      }
    </style>

</head>
<body>
  {% include "nav.html" %}
  {% block content %}{% endblock %}
  {% block footer %}
    <footer>
      <p>Copyright &copy; 2016. All rights reserved</p>
    </footer>
  {% endblock footer %}
</body>
</html>

myproject/core/templates/core/director.html
{% extends "base.html" %}

{% block title %}
    <title>Director</title>
{% endblock title %}

{% block content %}

    <h2>Você está logado</h2>

    <h3><b>e-mail:</b> {{ user.email }}</h3>
    <h3><b>Grupo:</b> {{ user.groups.first.name }}</h3>

{% endblock content %}

myproject/core/templates/core/logged.html
{% extends "base.html" %}

{% block title %}
    <title>Logged</title>
{% endblock title %}

{% block content %}

    <h2>Você está logado como {{ user.email }}</h2>

{% endblock content %}

myproject/core/templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Welcome</h1>
{% endblock content %}

myproject/core/templates/nav.html
<!-- Menu -->
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="current"><a href="{% url 'core:home' %}"><span class="glyphicon glyphicon-home"></span> Home</a></li>
        <li><a href="/accounts/register/">Registrar</a></li>
      </ul>
    </div>
  </div>
</div>